# Generated by Django 4.0 on 2024-10-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Street',
            field=models.CharField(max_length=100),
        ),
    ]
