# Generated by Django 4.0 on 2024-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_alter_residentialrent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'commercial_lease',
            },
        ),
        migrations.AddField(
            model_name='land',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlease',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landrent',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landresale',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residential',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residentiallease',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residentialrent',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residentialresale',
            name='Property_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signupdetails',
            name='Customer_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
