# Generated by Django 4.0 on 2024-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0004_commerciallease_land_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='landlease',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='landrent',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='landresale',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='residential',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='residentiallease',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='residentialrent',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='residentialresale',
            name='Customer_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlease',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='landrent',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='landresale',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='residential',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='residentiallease',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='residentialrent',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='residentialresale',
            name='Property_Id',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
